language: node_js
addons:
  ssh_known_hosts:
  - quasar.cross-solution.de
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
  - "$HOME/.composer/cache"
  - "$HOME/.yarn"
matrix:
  fast_finish: true
  include:
  - php: '7.2'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_ccc4868af128_key -iv $encrypted_ccc4868af128_iv
  -in .travis/deploy.enc -out ~/.ssh/id_ed25519 -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_ed25519
- ssh-add ~/.ssh/id_ed25519
- curl -LO https://deployer.org/deployer.phar
- chmod +x deployer.phar
install:
- yarn
- NODE_ENV=production yarn build
script:
- echo "TODO create tests"
deploy:
- provider: script
  skip_cleanup: true
  script: "./deployer.phar deploy"
  on:
    branch: master
